### ISSUE TITLE
No Longer Compatibility

### ISSUE THREAD

**Issue by Srihari-CS** [MolsonCAD/DeluxeJournal#8]
After updating to the latest stardew valley 1.6.14 Deluxe Journal is not longer compatible.
SMAPI completely skips over the mod and just says the mod is no longer compatible. I hope it is possible fix it
https://smapi.io/log/833a49c7b84d4d10b55d81790225051c

**Comment by MolsonCAD** [comment]
Thanks, SDV 1.6.9+ does include some breaking changes. I'll start working on an update.
